steps:
    - name: "gcr.io/cloud-builders/docker"
      args: ["build", "--tag=gcr.io/$PROJECT_ID/readmeio", "."]
    - name: "gcr.io/${PROJECT_ID}/readmeio"
      args: ["-h"]
  
  images: ["gcr.io/$PROJECT_ID/readmeio"]
  tags: ["cloud-builders-community"]